import os
from game.point import Point

MAX_X = 260
MAX_Y = 80
FRAME_LENGTH = 0.05
PATH = os.path.dirname(os.path.abspath(__file__))
ARTIFACTS = 30

ENEMY_FIRE_DAMAGE = 40
ENEMY_COLLISION_DAMAGE = 10
ENEMY_FIRE_CHANCE = 10 # Percent chance per frame to fire
DISTANCE_BETWEEN_ENEMIES = 20
TOTAL_ENEMIES = 20

FIRE_COST = 10
THRUST_COST = 10
SHIELD_REGEN = 1 # Percent per frame

FALCON_THRUST   = Point(3, 1)
FALCON_SHIELDS  = 150
FALCON_ENGINES  = 100
FALCON_WEAPONS  = 100
FALCON_HULL     = 400

XWING_THRUST   = Point(3, 1)
XWING_SHIELDS  = 150
XWING_ENGINES  = 100
XWING_WEAPONS  = 100
XWING_HULL     = 400

AWING_THRUST   = Point(6, 2)
AWING_SHIELDS  = 150
AWING_ENGINES  = 100
AWING_WEAPONS  = 100
AWING_HULL     = 400

YWING_THRUST   = Point(2, 1)
YWING_SHIELDS  = 150
YWING_ENGINES  = 100
YWING_WEAPONS  = 100
YWING_HULL     = 400